### ISSUE TITLE
Just curious, is there a public URL for this?

### ISSUE THREAD

**Issue by snewcomer** [fully-forged/memento#2]
Or just meant to be used personally?

**Comment by cloud8421** [comment]
Thanks for checking out the project!

Yes, it is meant to be used personally.

I thought about a demo instance, but it would require maintaining a public instance with different credentials and some operational costs so it's not on the table for now.

**Comment by snewcomer** [comment]
Awesome!  Be glad to help if there were issues/features you thought of implementing!

**Comment by cloud8421** [comment]
Thanks for the offer, I have some ideas, just need to formalize them on a board.

**Comment by cloud8421** [comment]
@snewcomer I've now added a project board if you're still interested.
